<?php
$params=array(
	"name"=>"aaaa",
	"category"=>"AAAA",
	"title"=>"API名テキストテキストテキスト",
	"endpoint"=>$this->params["root"]."a1/aaaa",
	"caption"=>"説明文テキストテキストテキストテキスト\nテキストテキストテキストテキストテキストテキスト",
	"method"=>"post",
	"encoding"=>"UTF-8",
	"autholity"=>"base64_encode({service_secret}:{lisence_key})",
	"output"=>"json",
	"testForm"=>array(
		//"url"=>$this->params["root"]."a1/aaaa",
		"service_secret"=>"xxxxxxxxxxxxxxxxxx",
		"lisence_key"=>"xxxxxxxxxxxxxx",
	),
	"Request"=>array(
		"aaaa"=>array(
			"name"=>"入力名AAAA",
			"type"=>"text",
			"required"=>true,
			"placeholder"=>"aaaaaaaaaaaa...",
		),
		"bbbb"=>array(
			"name"=>"入力名BBB",
			"type"=>"text_long",
			"caption"=>"備考欄テキストテキストテキストテキスト",
			"placeholder"=>"bbbbbbb...",
		),
		"cccc"=>array(
			"name"=>"入力名BBB",
			"type"=>"radio",
			"required"=>true,
			"select"=>array(1=>"選択1",2=>"選択2"),
		),
		"dddd"=>array(
			"name"=>"入力名BBB",
			"type"=>"select",
			"select"=>array(1=>"選択1",2=>"選択2",3=>"選択3"),
		),
		"eeee"=>array(
			"name"=>"入力名eee",
			"multi"=>array(
				"fff"=>array(
					"type"=>"text",
					"name"=>"入力名fff",
				),
				"ggg"=>array(
					"type"=>"number",
					"name"=>"入力名ggg",
				),
				"hhh"=>array(
					"name"=>"入力名hhh",
					"caption"=>"説明文hhhhhhhhhhh.....",
				),
			),
		),
		"iii"=>array(
			"name"=>"入力名iii",
			"required"=>true,
		),
	),
	"Response"=>array(
		"nnnn"=>array(
			"name"=>"出力名nnnn",
			"type"=>"text",
			"caption"=>"説明文text..",
		),
		"mmmm"=>array(
			"name"=>"出力名mmmm",
			"type"=>"text",
		),
		"llll"=>array(
			"name"=>"出力名llll",
			"type"=>"text",
		),
		"ooo"=>array(
			"name"=>"出力名ooo",
			"multi"=>array(
				"ppp"=>array(
					"name"=>"出力名ppp",
					"caption"=>"説明文テキストテキストテキストテキストテキストテキスト",
				),
				"qqq"=>array(
					"name"=>"出力名qqq",
					"caption"=>"説明文テキストテキストテキストテキストテキストテキスト",
				),
			),
		),
		"rrr"=>array(
			"name"=>"出力名rrr",
			"type"=>"number",
		),
	),
);
?>